spring:
  datasource:
    username: root
    password: admin0001112
    url: jdbc:mysql://localhost:3306/RUNOOB?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: mysql
  thymeleaf:
    cache: false
    encoding: utf-8

mybatis:
  typeAliasesPackage: com.wind.entity
  mapperLocations: classpath:mapper/*.xml

server:
  port: 8090
  servlet:
    context-path: /
